### ISSUE TITLE
Passage UniqueID

### ISSUE THREAD

**Issue by angel-daza** [Semantics-of-Sustainability/tempo-embeddings#40]
When implementing the database, each embedding belongs to one passage. The `hash()` of each passage is being used to generate an ID and insert it into the database. This is helpful so the code can skip the computing of an embedding if it already exists in the database. The problem is that the value returned by the `hash()` function is not entirely the same when the code is executed in a different context (for example, if the notebook is restarted, the has value returned is different, even though in theory it shouldn't, and the same passage is inserted again in the database). 

Could we come up with another way of creating Passage IDs that are always unique? It would be a plus if the ID is informative (for example, an ID can be the concatenation of the name of the original file, the issue number, the index of the passage inside that file, and the first 5 characters of the passage, etc...)

**Comment by carschno** [comment]
On second thought, uniqueness seems to be important here, so I think the [UUID module](https://docs.python.org/3/library/uuid.html) might be more appropriate.

**Comment by carschno** [comment]
To make the plan more specific:

- [ ] add a `Passage.uuid()` method (using Python's [uuid module](https://docs.python.org/3/library/uuid.html)), that uses text and metadata
- [ ] Use the Passage.uuid() as unique ID for database

The `Passage.__hash__()` therefore does not need to change, but will no longer be used for the database IDs.
